[build]
  publish = "public"
  command = "echo No build command"
  node_bundler = "esbuild"
  functions = "src"

[dev]
  publish = "public"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
